### ISSUE TITLE
Consider transitional format to improve existing replay compression

### ISSUE THREAD

**Issue by Wesmania** [FAForever/faf-aio-replayserver#14]
See #13. If we use better compression, we can save about 40% of disk space taken by replays. All we need is adding a version field to replay headers, plus a compression type field.

This will need java client support. I'd also like to know if we're interested in saving disk space.

**Comment by Wesmania** [comment]
See https://github.com/FAForever/faf-aio-replayserver/pull/17. Client support is at https://github.com/FAForever/faf-java-commons/pull/33.

**Comment by Brutus5000** [comment]
We did this!

**Comment by Wesmania** [comment]
yay
